spring:
  application:
    name: customer-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/customerdb}

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health,info
